filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app-logs/fastapi-app/*.log
      - /app-logs/fastapi-consumer1/*.log
      - /app-logs/fastapi-consumer2/*.log

# Try to decode JSON payloads written into the `message` field so inner keys
# become searchable fields (event, service, @timestamp, etc.). This helps
# when the app wrote a JSON string into the message field.
processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true
      max_depth: 2
  # Optional: convert @timestamp from inner payload into event timestamp
  - timestamp:
      field: "@timestamp"
      layouts:
        - "2006-01-02T15:04:05.000000Z"
        - "2006-01-02T15:04:05Z"
        - "2006-01-02T15:04:05.000000+00:00"
        - "2006-01-02T15:04:05.000000+00:00"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
